// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgwlyvwstgfxekjumkmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnd2x5dndzdGdmeGVranVta21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MjM3MTQsImV4cCI6MjA2NDI5OTcxNH0.ZeLVF4pF7wmSybA3oekd4GJx-Id5K9DXIGbFwo4B0J0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);